### ISSUE TITLE
Crash in weather feature

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-android#1187]
I saw this pop up on the console while working on the app.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.onebusaway.android.io.request.weather.models.CurrentForecast.getIcon()' on a null object reference
	at org.onebusaway.android.ui.HomeActivity.setWeatherData(HomeActivity.java:2004)
	at org.onebusaway.android.ui.HomeActivity.onWeatherResponseReceived(HomeActivity.java:2029)
	at org.onebusaway.android.io.request.weather.WeatherRequestTask.onPostExecute(WeatherRequestTask.java:29)
	at org.onebusaway.android.io.request.weather.WeatherRequestTask.onPostExecute(WeatherRequestTask.java:8)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by aaronbrethorst** [comment]
fyi @amrhossamdev

**Comment by amrhossamdev** [comment]
Investigating, what is the selected region?
