### ISSUE TITLE
Travis build failures - ShellCommandUnresponsiveException

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#247]
We're seeing a lot of build failures on the first and even second execution of PRs on Travis, which then pass on the next attempt.

Here's what the error looks like on failures:

~~~
:onebusaway-android:connectedAndroidTest
09:48:14 E/Device: Error during shell execution: null
Unable to install /home/travis/build/OneBusAway/onebusaway-android/onebusaway-android/build/outputs/apk/onebusaway-android-debug.apk
com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installPackages(Device.java:927)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:105)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:125)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:513)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:390)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:359)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:566)
	at com.android.ddmlib.Device.createMultiInstallSession(Device.java:987)
	at com.android.ddmlib.Device.installPackages(Device.java:884)
	... 9 more
com.android.builder.testing.ConnectedDevice > runTests[test(AVD) - 5.0.1] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException
		at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:108)
null
com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:108)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:125)
	at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.ddmlib.InstallException
	at com.android.ddmlib.Device.installPackages(Device.java:927)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:105)
	... 8 more
Caused by: com.android.ddmlib.ShellCommandUnresponsiveException
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:513)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:390)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:359)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:566)
	at com.android.ddmlib.Device.createMultiInstallSession(Device.java:987)
	at com.android.ddmlib.Device.installPackages(Device.java:884)
	... 9 more
:onebusaway-android:connectedAndroidTest FAILED
FAILURE: Build failed with an exception.
~~~

I believe this is the underlying issue on Travis:
https://github.com/travis-ci/travis-ci/issues/3110

I'm leaving this open for now just so everyone knows why they are failing, and I'll close this out when we have some type of resolution.

**Comment by barbeau** [comment]
Based on a response to the [AOSP issue](https://code.google.com/p/android/issues/detail?id=69735#c9) for this original problem in the Android tools, there is now apparently an (undocumented) environmental variable `ADB_INSTALL_TIMEOUT` where you can set ddmlib timeout.  See this [.travis.yml](https://github.com/ardock/android-testing/blob/ttt-colors/.travis.yml) for an example:

~~~
language: android

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email: false

env:
  global:
    - INSTALL_PKGS='build-tools-21.1.2'
    - UPDATE_PKGS='platform-tools,tools,extra-android-m2repository,extra-google-m2repository'
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - AVD_DEBUG='init,avd_config,nand_limits,keys,adb,adbserver,adbclient'
    ...
~~~

I'm going to give this a shot and see if it works.

**Comment by barbeau** [comment]
Made this change in both develop and master.

**Comment by barbeau** [comment]
Also created this SO post with the problem and solution:
http://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception/28949723#28949723

**Comment by SjoerdvGestel** [comment]
90% of builds fail due to com.android.builder.testing.api.DeviceException: com.android.ddmlib.ShellCommandUnresponsiveException
