### ISSUE TITLE
develop branch crashes when GTFS shapes.txt isn't provided

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#270]
As discussed on the mailing list (https://groups.google.com/d/msg/onebusaway-developers/wK5VHHA1DqQ/pOstfHcfvVQJ), the current behavior of OBA when building the transit bundle is to omit the polyline when shapes.txt isn't provided in the GTFS data.

As a result, in the stops-for-route API response from the OBA server, the "polylines" element is empty for all routes.  This prevents the apps from showing the route geometry (i.e., stops for the route) on the map when they drill down to a single route on the map.  However, in the `develop` branch we don't consider the possibility that the polylines aren't provided, and the app crashes:

~~~
java.lang.IllegalStateException: no included points
            at com.google.android.gms.common.internal.zzu.zza(Unknown Source)
            at com.google.android.gms.maps.model.LatLngBounds$Builder.build(Unknown Source)
            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.zoomToRoute(BaseMapFragment.java:704)
            at org.onebusaway.android.map.RouteMapController.onLoadFinished(RouteMapController.java:158)
            at org.onebusaway.android.map.RouteMapController.onLoadComplete(RouteMapController.java:174)
            at org.onebusaway.android.map.RouteMapController.onLoadComplete(RouteMapController.java:39)
            at android.support.v4.content.Loader.deliverResult(Loader.java:104)
            at org.onebusaway.android.map.RouteMapController$RoutesLoader.deliverResult(RouteMapController.java:265)
            at org.onebusaway.android.map.RouteMapController$RoutesLoader.deliverResult(RouteMapController.java:235)
            at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
            at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
            at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
            at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5431)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
~~~

Steps to reproduce:

1.  Go to any stop and show the arrival times
2.  Tap on an arrival time for a route that doesn't have shape data
3.  Select "Show route information"
4.  Tap on the map icon in the Actoin Bar

Here's an example response without polylines:
http://194.89.230.196:8080/api/where/stops-for-route/6677_4.json?includePolylines=true&app_ver=38&key=v1_BktoDJ2gJlu6nLM6LsT9H8IUbWc%3DcGF1bGN3YXR0c0BnbWFpbC5jb20%3D

~~~
{

    code: 200,
    currentTime: 1434637770619,
    data: {
        entry: {
            polylines: [ ],
            routeId: "6677_4",
            stopGroupings: [

~~~

...and one with:
http://api.tampa.onebusaway.org/api/api/where/stops-for-route/Hillsborough%20Area%20Regional%20Transit_5.json?includePolylines=true&key=v1_BktoDJ2gJlu6nLM6LsT9H8IUbWc%3DcGF1bGN3YXR0c0BnbWFpbC5jb20%3D

~~~
{
    code: 200,
    currentTime: 1434637837375,
    data: {
        entry: {
            polylines: [
                {
                    length: 427,
                    levels: "",
                    points: "_{hjDfubvNpIC?gE?qEA}LA_@AgBCUEc@Qs@c@u@GMKo@Ke@?_@?c@@i@?yE?{@?cABqGnA?^AZGJELCv@[j@KxA?N?N?T?P?ZAVENDr@g@^Yj@_@n@a@JAh@Gf@Gd@Ab@Bn@FnAb@j@XNHTF`@Dr@?Z?jD@V?R?lE?@wG?sH?]@_@?[LcAF]Lg@D[DKRk@FSTq@HQRw@PiA@GH_AB{BzGAh@@~@@|A@r@@AlJ?bE?Vd@?jBBdD?hEBhB?Z?nAC`D?N?dAB~B?N?nBCxABd@?dC?X?v@?pD?`A?`C?|C?|A?vC?bE?b@?jD?H?hB?~@@tC@nD?zB?|C?pEAV?bA?P?x@@b@?V?^?jA@J?d@?z@BhA?d@?V?p@?Z?j@?fB?r@?pC?`@?r@?~D?f@@BN@@JJNDNCJGJMP?nGDfLCpAK`AK|@Qr@OfBe@h@YnCuA|@e@XQNEVCL?LJPDPEFIHKNGXMzAe@hDs@|@O`AIP?bACn@EvBCdDBtAFv@DdAJ~@Jh@JxAPn@HXF`@Dp@JVBPBt@JzARRBp@Hl@HrANvADf@?t@?\Ax@Cd@Gh@GnCi@lCm@nA[lBa@v@Mr@GbAKb@Cb@ApCCtECfA?nCAv@AH?P@VDBJLHFBH@RENOPAPGrAAjC?xC?jC?pC?lC?pC?rC?fB?d@?`AApA?vA?zA?xA@xG?`I@F?r@?dD?P?J?`@?nB?bA?rB@?~A@fB?`B?pB?zGBfC?hC@|B?lCAdCE`E@pAj@?tA?lAAbDAdB?pA?t@?~BAjCAf@@hB?L?N?vB?P?`C?jC@rC?V?hBAfDDrC?V?|BAtCA\AnBAfA?nA?jBA^?tC?v@?~AC`@?lB@bAAhA?x@?d@?f@?zC?tGAbDCAdI?|G?L?Z?r@?bA?T?b@Av@@RBRBNHNHN\X^VX\LNDPHd@?ZAhH?lE?L?H@pC?b@Bj@Dr@ArE@fG?p@?jB?l@dCAbDAx@@d@?pA@N?x@?`@?b@?hA?`@?lC?dC?M`A?lLAvC@ZDVBd@@f@?vE?jAE|AE`@Cf@?bA?nC?f@A`C?Z?zA@hEBn@BP@PB`@?Z?fC?Z?lC?zC?fBDpELbEBb@@ZHX@|C?vA?dA?`@?P?n@?z@?`@?b@@dB@bD@tFAdQpDdH|D?pD??uC?{G~E@zE?zA?\?`@?b@?xD?@oC|D?ApCMQQ_@KCY?U?"
~~~

**Comment by barbeau** [comment]
Fixed in `develop` branch via https://github.com/OneBusAway/onebusaway-android/commit/8fa55334c4d19441434820e9c96b0236f7085545
