### ISSUE TITLE
Crash when searching prior to location initialization

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#273]
Reported by Fire Phone user, for `develop` branch:

>Steps to reproduce:
>1. Disable Location Services in Settings
>2. Launch app for the 1st time
>3. Search for a bus stop > crash

 >06-24 13:13:45.254: E/AndroidRuntime(24303): FATAL EXCEPTION: ModernAsyncTask # 1
06-24 13:13:45.254: E/AndroidRuntime(24303): Process: com.joulespersecond.seattlebusbot, PID: 24303
06-24 13:13:45.254: E/AndroidRuntime(24303): java.lang.RuntimeException: An error occured while executing doInBackground()
06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.q$3.done(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.run(FutureTask.java:242)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.lang.Thread.run(Thread.java:841)
06-24 13:13:45.254: E/AndroidRuntime(24303): Caused by: java.lang.NullPointerException
06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.io.request.ObaRoutesForLocationRequest$Builder.<init>(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.y(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.f(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at org.onebusaway.android.ui.br.d(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.a.e(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.b.a(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.b.a(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at android.support.v4.a.q$2.call(Unknown Source)
06-24 13:13:45.254: E/AndroidRuntime(24303): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-24 13:13:45.254: E/AndroidRuntime(24303): ... 3 more
 
>The problem is fixed after enabling LBS and wait for it to get my current location before performing a search

**Comment by barbeau** [comment]
Here's an un-obfuscated stack trace:

~~~
06-24 16:56:11.356   32632-1692/com.joulespersecond.seattlebusbot E/AndroidRuntime﹕ FATAL EXCEPTION: ModernAsyncTask #3
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NullPointerException
            at org.onebusaway.android.io.request.ObaRoutesForLocationRequest$Builder.<init>(ObaRoutesForLocationRequest.java:41)
            at org.onebusaway.android.ui.SearchResultsFragment$MyLoader.getRoutes(SearchResultsFragment.java:297)
            at org.onebusaway.android.ui.SearchResultsFragment$MyLoader.loadInBackground(SearchResultsFragment.java:337)
            at org.onebusaway.android.ui.SearchResultsFragment$MyLoader.loadInBackground(SearchResultsFragment.java:284)
            at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
            at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)
~~~

**Comment by barbeau** [comment]
Fixed in `develop` branch via https://github.com/OneBusAway/onebusaway-android/commit/86c4722df9c55865301635c8eb1271ac8688b700
