### ISSUE TITLE
StackOverflowError when using Arrival Info Style B on Android 2.3 device

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#275]
When trying to view arrival times on an HTC EVO Shift with Android 2.3.4, the Agency Y demo app crashes and I get the following trace:

~~~
06-26 10:37:16.790    1355-1511/? D/lib_locapi﹕ loc_eng_report_position: valid mask = 0x6060, sess status = 0
06-26 10:37:16.820    4372-4372/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.StackOverflowError
            at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:182)
            at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:261)
            at java.util.concurrent.CopyOnWriteArrayList.removeRange(CopyOnWriteArrayList.java:569)
            at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:366)
            at java.util.concurrent.CopyOnWriteArrayList.remove(CopyOnWriteArrayList.java:376)
            at android.view.ViewTreeObserver.removeOnPreDrawListener(ViewTreeObserver.java:377)
            at android.widget.TextView.onDraw(TextView.java:4132)
            at android.view.View.draw(View.java:6970)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.widget.AbsListView.dispatchDraw(AbsListView.java:1480)
            at android.widget.ListView.dispatchDraw(ListView.java:3186)
            at android.view.View.draw(View.java:7082)
            at android.widget.AbsListView.draw(AbsListView.java:2588)
            at android.view.View.buildDrawingCache(View.java:6695)
            at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1345)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1591)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.drawChild(SlidingUpPanelLayout.java:1024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.draw(SlidingUpPanelLayout.java:1067)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.View.draw(View.java:6973)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:500)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1732)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1459)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1730)
            at android.view.ViewGroup.dispatchDr
06-26 10:37:16.850    1355-1487/? W/ActivityManager﹕ Force finishing activity org.agencyy.android/org.onebusaway.android.ui.HomeActivity
06-26 10:37:16.870    1355-1504/? D/RPC﹕ read RPC packet
~~~

Based on these two StackOverflow posts:

* http://stackoverflow.com/a/19854263/937715
* http://stackoverflow.com/a/16920207/937715

...it appears that the thread stack sizes for Android 2.3 are 12KB, while Android 4.0 and higher is 16KB.  With the CardViews and nested arrival times in Style B, we're exceeding the stack size which leads to the StackOverflowError.

Our options seem to be:

* Try to reduce the depth of the View hierarchy on Style B
* Only allow Style B on Android 4.0 and higher

**Comment by barbeau** [comment]
I tried a quick simplification of the view hierarchy (https://github.com/OneBusAway/onebusaway-android/commit/910100f8275f557a168d798a00f42e8dd80175db), but that didn't help.  I then tried Yorks app on the same device, and that does work ok (i.e., no StackOverflowError).  I then checked out the commit that added York's layout to OBA Android (37b4565c746f99cb631931035c312f825fd09b43), and I got the error again.  The main difference between York's app and ours is that we have the view hierarchy in a sliding panel, and York does not.

So, what seems to be breaking on the device is the York layout in the sliding panel - that is too much for the limited thread stack size of Android 2.3 to handle.

I'm going to try to simplify the hierarchy a bit more, since this is good for performance anyway, but we may end up only being able to support the Style B presentaton on Android 4.0 and higher.

**Comment by barbeau** [comment]
So even with removing the TableLayout and TableRows, to pare back to the bare minimum needed to represent the Card view for Style B (as seen below), I'm still getting the StackOverflowError.  So, I don't think there is any way we can get this to work in the sliding drawer on Android 2.3 (or at least this device with Android 2.3.4 - I'd be interested in trying this on other 2.3 devices, but unfortunately I don't think I have any others handy).  

![image](https://cloud.githubusercontent.com/assets/928045/8282984/45dd5dd6-18c2-11e5-99db-7237dffb9554.png)

On a related note, I've noticed that the Google app (i.e., Google Now) on this device doesn't display any Cards in a scrolling view either, probably for the same reason.  It just shows up as a search box at the top of the screen, and directs to you the Google search webpage for anything you enter....and I was going to attach a screenshot here of that, but apparently I can't take screenshots in Android Studio with this device either - it shows up as a blank checkboard canvas in the screenshot view screen, and I see `IllegalArgumentException: image == null` in the bottom status bar of Android Studio.  Looks like Gingerbread is going by the wayside.

**Comment by barbeau** [comment]
Well, it looks like this issue isn't universal for all Gingerbread devices.  I Just tested the normal Style B Card view on a Samsung Epic 4G (basically, a Galaxy S) w/ Android 2.3.6, and the Card view works fine and this StackOverflowError doesn't occur.

**Comment by barbeau** [comment]
I completely re-wrote the layout for the Style B list item in https://github.com/OneBusAway/onebusaway-android/commit/b6304173645c1e912088ac99a61777061d936453, removing the static TableLayout/TableRow implementation and replacing it with simpler relative/linear layouts, and it looks like that (along with https://github.com/OneBusAway/onebusaway-android/commit/910100f8275f557a168d798a00f42e8dd80175db) removed enough of the hierarchy that Style B now works on both the HTC and Samsung devices with Gingerbread.  So, we can call this fixed in `develop` branch as of https://github.com/OneBusAway/onebusaway-android/commit/b6304173645c1e912088ac99a61777061d936453.

If anyone else has a Gingerbread device that they could try this on to make sure it works, that would be very helpful.  If you want to test, just be aware that because of https://github.com/OneBusAway/onebusaway-android/issues/272 you have to assemble the release version of the app so Proguard strips out all the extra methods.  So, to test run `gradlew assembleAgencyyGoogleRelease` and sign it with your own cert (see [Readme](https://github.com/OneBusAway/onebusaway-android/blob/master/README.md#release-builds)), and then browse to `/onebusaway-android/build/outputs/apk` and do `adb install onebusaway-android-agencyY-google-release.apk`.
