### ISSUE TITLE
NPE caused by ObaStopsForLocationResponse$Data.access$100(ObaStopsForLocationResponse.java:30)

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#277]
In production/master branch - this seems to be happening far more often in v1.7.9 (33 times) than v1.7.8 (1 time).

Stack trace from developer console:

~~~
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
at com.joulespersecond.oba.request.ObaStopsForLocationResponse$Data.access$100(ObaStopsForLocationResponse.java:30)
at com.joulespersecond.oba.request.ObaStopsForLocationResponse.getStops(ObaStopsForLocationResponse.java:60)
at com.joulespersecond.seattlebusbot.SearchResultsFragment$MyLoader.loadInBackground(SearchResultsFragment.java:347)
at com.joulespersecond.seattlebusbot.SearchResultsFragment$MyLoader.loadInBackground(SearchResultsFragment.java:280)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
~~~

User comments indicate it either happens when searching or when opening the app.  v1.7.9 was a fairly simple release with only two changes (add Finnish translation and hide softkeyboard when leaving search fragment), so I'm not sure what's causing this.  Will need to investigate further...

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/18b8b72c6fd9cb4fb647e56de60b75849bda97d9.
