### ISSUE TITLE
AdapterTest.testAdapterB test is erroring out

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#279]
For `develop` branch, it shows the error:

~~~
android.view.InflateException: Binary XML file line #79: Error inflating class android.widget.ImageButton
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at org.onebusaway.android.util.ArrayAdapter.getView(ArrayAdapter.java:67)
at org.onebusaway.android.adapter.test.AdapterTest.testAdapterB(AdapterTest.java:77)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:607)
... 24 more
Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 13
at android.content.res.TypedArray.getDrawable(TypedArray.java:747)
at android.view.View.<init>(View.java:3760)
at android.widget.ImageView.<init>(ImageView.java:139)
at android.widget.ImageButton.<init>(ImageButton.java:86)
at android.widget.ImageButton.<init>(ImageButton.java:82)
at android.widget.ImageButton.<init>(ImageButton.java:78)
... 27 more
~~~

Based on some searching [SO posts](http://stackoverflow.com/questions/26524048/upgrading-to-sdk-21-error-inflating-class-android-support-v7-internal-widget-a), it appears this is due to the use of the `android:background="?attr/selectableItemBackground"` element for the ImageButtons in `arrivals_list_item_style_b.xml`.  Apparently these are only found when a theme is applied, and currently this test is running outside a theme.  Our choices are to run this test in the context of a theme, or revise this test to avoid the error.

**Comment by barbeau** [comment]
Failure on Travis:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/74317674

**Comment by barbeau** [comment]
Fixed in develop via https://github.com/OneBusAway/onebusaway-android/commit/3a5c51545cc662a485a1818b453a3fa5ddf9b876.
