### ISSUE TITLE
NPE on startup due to null GoogleMap

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#296]
For `develop` branch:

When starting the app on a Samsung Galaxy S3 with Android 4.4.4 (CyanogenMod):

~~~
    Process: com.joulespersecond.seattlebusbot, PID: 11792
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.getLatitudeSpanInDecDegrees(BaseMapFragment.java:607)
            at org.onebusaway.android.map.StopsRequest.<init>(StopMapController.java:57)
            at org.onebusaway.android.map.StopMapController.onCreateLoader(StopMapController.java:249)
            at org.onebusaway.android.map.StopMapController.<init>(StopMapController.java:172)
            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setMapMode(BaseMapFragment.java:325)
            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.initMap(BaseMapFragment.java:224)
            at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onCreateView(BaseMapFragment.java:211)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at org.onebusaway.android.ui.HomeActivity.onStart(HomeActivity.java:285)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
~~~

Changing to the new async callback `onMapReady()` may fix this.

**Comment by barbeau** [comment]
Looks like this was caused by Google Play Services being out of date on this device, and needing an update from the Play Store.  The current code ends up throwing an NPE in that situation.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/f295b97bbd6e480190d5623b44e728fc0dd2e4e4.

**Comment by barbeau** [comment]
Apparently this async method doesn't exist on Amazon?

This failed:
https://travis-ci.org/OneBusAway/onebusaway-android/builds/81476987

**Comment by barbeau** [comment]
Full error trace on Amazon:

~~~
Error:(32, 29) error: cannot find symbol class OnMapReadyCallback
Error:(102, 45) error: cannot find symbol class OnMapReadyCallback
Error:(190, 17) error: cannot find symbol method getMapAsync(BaseMapFragment)
Error:(212, 5) error: method does not override or implement a method from a supertype
~~~

**Comment by barbeau** [comment]
Apparently OnMapReadyCallback is available in the newest version of the Amazon Maps library.  Looking to update now...

**Comment by barbeau** [comment]
Amazon build should now be fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/3550343c9d130e9bc0252377bb06e51bae46d247.
