### ISSUE TITLE
v2.0.4 alpha is crashing

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#300]
For `develop` branch:

On starting the app, this happens:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference
	at org.onebusaway.android.util.UIHelp.setupSearch(UIHelp.java:97)
	at org.onebusaway.android.ui.HomeActivity.onCreateOptionsMenu(HomeActivity.java:493)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2926)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:277)
	at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:275)
	at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1117)
	at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1399)
	at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
	at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:123)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5431)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
~~~

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/ae0791334137babfb26fbb578af046bdfcbb3578.  I'll do another alpha release to fix this.
