### ISSUE TITLE
NPE when choosing "Show trip details" for scheduled time

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#317]
When tapping on a scheduled arrival and choosing "Show trip details", the app crashes with:

~~~
 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.onebusaway.android.io.elements.ObaTripStatus.getActiveTripId()' on a null object reference
            at org.onebusaway.android.ui.TripDetailsListFragment.setUpHeader(TripDetailsListFragment.java:230)
            at org.onebusaway.android.ui.TripDetailsListFragment.setTripDetails(TripDetailsListFragment.java:195)
            at org.onebusaway.android.ui.TripDetailsListFragment.access$500(TripDetailsListFragment.java:52)
            at org.onebusaway.android.ui.TripDetailsListFragment$TripDetailsLoaderCallback.onLoadFinished(TripDetailsListFragment.java:351)
            at org.onebusaway.android.ui.TripDetailsListFragment$TripDetailsLoaderCallback.onLoadFinished(TripDetailsListFragment.java:340)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:395)
            at android.support.v4.content.Loader.deliverResult(Loader.java:104)
            at org.onebusaway.android.ui.TripDetailsListFragment$TripDetailsLoader.deliverResult(TripDetailsListFragment.java:395)
            at org.onebusaway.android.ui.TripDetailsListFragment$TripDetailsLoader.deliverResult(TripDetailsListFragment.java:363)
            at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
            at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
            at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
            at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
            at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5431)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
~~~

**Comment by barbeau** [comment]
"Trip Details" is the new feature that was just added in https://github.com/OneBusAway/onebusaway-android/pull/295.

**Comment by barbeau** [comment]
It appears the issue here is that OBA has two ways to represent "no current real-time info".  The first is that `predicted = false` in the status element.  This means we don't have a prediction for the vehicle, but we do have other information that may be interpolated/extrapolated from past updates.  The second is that the `status` element in the response can be `null`.  This occurs if the trip is far in the future (e.g., several hours) and OBA doesn't have any real-time info about that trip.  The second situation is what is causing the NPE above.

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/issues/319.
