### ISSUE TITLE
Move to runtime permissions model for Android 6.0

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#330]
In Android 6.0, there are new runtime permissions, instead of install-time permissions.  We'll need to move to runtime permissions at some point in the near future.

According to this article:
http://www.fulcrumapp.com/blog/fulcrum-android-and-marshmallow-runtime-permissions/

...runtime permissions aren't enforced until we change `targetSdkVersion` to 23 or higher.

Above article has good description of which permissions are "NORMAL" and don't require user prompts, and which are "DANGEROUS" and require user prompts - it points to this link:
http://developer.android.com/guide/topics/security/normal-permissions.html

Here's the official Google short video on moving to runtime permissions:
https://www.youtube.com/watch?v=iZqDdvhTZj0

**Comment by barbeau** [comment]
Here's a link for how to manage runtime permissions with Play Services 8.1:
http://android-developers.blogspot.com/2015/09/google-play-services-81-and-android-60.html

**Comment by barbeau** [comment]
It looks like some users are turning off location permissions for the app (both v1.7.9 and v2.0.13) from the Android system settings, which is causing these crashes:

~~~
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at com.google.android.gms.internal.lx$a$a.bW(Unknown Source)
	at com.google.android.gms.internal.ly.getLastLocation(Unknown Source)
	at com.google.android.gms.internal.lz.getLastLocation(Unknown Source)
	at com.google.android.gms.location.LocationClient.getLastLocation(Unknown Source)
	at com.joulespersecond.seattlebusbot.util.LocationHelp.getLocation2(LocationHelp.java:103)
	at com.joulespersecond.seattlebusbot.map.StopMapController.onLoadFinished(StopMapController.java:274)
	at com.joulespersecond.seattlebusbot.map.StopMapController.onLoadComplete(StopMapController.java:309)
	at com.joulespersecond.seattlebusbot.map.StopMapController.onLoadComplete(StopMapController.java:135)
	at android.support.v4.content.Loader.deliverResult(Loader.java:104)
	at com.joulespersecond.seattlebusbot.map.StopMapController$StopsLoader.deliverResult(StopMapController.java:378)
	at com.joulespersecond.seattlebusbot.map.StopMapController$StopsLoader.deliverResult(StopMapController.java:340)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
	at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
~~~

When we update to the new permissions model we should make sure that these don't happen.  I believe users are warned by the platform that turning off permission for apps still using the install-time permission model can cause the app to be unstable.

**Comment by barbeau** [comment]
See more example stack traces at https://github.com/OneBusAway/onebusaway-android/issues/594.

**Comment by barbeau** [comment]
This is a little more urgent now that we're requiring users to accept the "Read user accounts" permission on install as a result of https://github.com/OneBusAway/onebusaway-android/commit/14f4f531cdc405c228737e039fa94041f4b92cb8.  Ideally users shouldn't need to opt into this unless they log into Embedded Social.

**Comment by barbeau** [comment]
A list of existing OBA Android app permissions and why we require them is at:
https://github.com/OneBusAway/onebusaway-android/blob/master/PERMISSIONS.md

**Comment by barbeau** [comment]
Here's a full list of permissions - as I document the protection level and implement fixes (see runtime-permissions branch) I'll check them off:

- [ ] `<uses-permission android:name="android.permission.INTERNET"/>`
- [ ] `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`
- [ ] `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
- [ ] `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>`
- [ ] `<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>`
- [ ] `<uses-permission android:name="android.permission.WAKE_LOCK"/>`
- [ ] `<uses-permission android:name="android.permission.VIBRATE"/>`
- [ ] `<uses-permission android:name="android.permission.READ_PHONE_STATE"/>`
- [ ] `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
- [ ] `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
- [ ] `<uses-permission android:name="com.android.launcher.permission.INSTALL_SHORTCUT"/>`
- [ ] `<uses-permission android:name="${applicationId}.permission.TRIP_SERVICE"/>`
- [ ] `<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>`
- [ ] `<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>`
