### ISSUE TITLE
Release builds crash with java.lang.IllegalStateException

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#342]
I was just trying to do another alpha release, and upon packaging the APK and installing it I get:

~~~
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:162)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5431)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:  Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at org.onebusaway.android.ui.HomeActivity.onCreate(HomeActivity.java:264)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6093)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:162) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5431) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
10-27 12:04:44.134 20284-20284/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
~~~

This doesn't happen on debug builds, only releases, so I'm assuming its an issue with Proguard, likely related to the change from using deprecated `ActionBarActivity` to `AppCompatActivity`:
https://github.com/OneBusAway/onebusaway-android/commit/b766fc6b05cdb44243100cfc9918b8c4371efdb9

**Comment by barbeau** [comment]
This AOSP issue seems related:
https://code.google.com/p/android/issues/detail?id=190237

I'm also seeing this in the Gradle output when doing the release:

~~~
:onebusaway-android:proguardObaGoogleRelease
Warning: com.google.android.gms.internal.zzhu: can't find referenced class android.security.NetworkSecurityPolicy
Warning: com.google.android.gms.internal.zzhu: can't find referenced class android.security.NetworkSecurityPolicy
Warning: com.google.android.gms.internal.zzhu: can't find referenced class android.security.NetworkSecurityPolicy
Warning: there were 3 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolved
class)
Exception while processing task
java.io.IOException: Please correct the above warnings first.
        at proguard.Initializer.execute(Initializer.java:473)
        at proguard.ProGuard.initialize(ProGuard.java:233)
        at proguard.ProGuard.execute(ProGuard.java:98)
        at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
        at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
        at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
        at com.android.builder.tasks.Job.runTask(Job.java:48)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.run
Task(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
        at java.lang.Thread.run(Thread.java:745)
:onebusaway-android:dexObaGoogleRelease UP-TO-DATE
:onebusaway-android:shrinkObaGoogleReleaseResources UP-TO-DATE
:onebusaway-android:validateReleaseSigning
:onebusaway-android:packageObaGoogleRelease
:onebusaway-android:zipalignObaGoogleRelease
:onebusaway-android:assembleObaGoogleRelease

BUILD SUCCESSFUL
~~~

**Comment by barbeau** [comment]
For the Proguard error:
http://stackoverflow.com/questions/32974025/com-google-android-gms-internal-zzhu-cant-find-referenced-class-android-securi

**Comment by barbeau** [comment]
Looks like this is actually caused by Google accidentally including AdMob in the dependencies of Play Services Analytics 8.1:
https://plus.google.com/+GoogleDevelopers/posts/HsSNWEQ6H4e

If I exclude the `play-services-ads` module I don't get the Proguard error, and the release build installs and runs without any problems:

~~~
    compile ('com.google.android.gms:play-services-analytics:8.1.0') {
        exclude module: 'play-services-ads' // See #342
    }
~~~

In Proguard rules you also need:

~~~
-dontwarn com.google.android.gms.ads.**
~~~

Thanks to this post for details (although it doesn't reference builds crashing at all, just APK size)
https://medium.com/google-developer-experts/warning-for-google-analytics-users-44b0096084e2#.4b3egtbxh

**Comment by barbeau** [comment]
Fixed in `develop` via https://github.com/OneBusAway/onebusaway-android/commit/e0c168aa07c69e769ba88c51650663f9297b0ff7.
