### ISSUE TITLE
NPE in VehicleOverlay at LayoutInflater.from()

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#379]
From Android Developer Console error reporting:

~~~
java.lang.NullPointerException
	at android.view.LayoutInflater.from(LayoutInflater.java:211)
	at org.onebusaway.android.map.googlemapsv2.VehicleOverlay$CustomInfoWindowAdapter.<init>(VehicleOverlay.java:579)
	at org.onebusaway.android.map.googlemapsv2.VehicleOverlay.<init>(VehicleOverlay.java:110)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.setupVehicleOverlay(BaseMapFragment.java:311)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.updateVehicles(BaseMapFragment.java:683)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadFinished(RouteMapController.java:400)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadComplete(RouteMapController.java:417)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadComplete(RouteMapController.java:375)
	at android.support.v4.content.Loader.deliverResult(Loader.java:104)
	at org.onebusaway.android.map.RouteMapController$VehiclesLoader.deliverResult(RouteMapController.java:366)
	at org.onebusaway.android.map.RouteMapController$VehiclesLoader.deliverResult(RouteMapController.java:339)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:223)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:61)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:461)
	at android.support.v4.content.ModernAsyncTask.access$500(ModernAsyncTask.java:47)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:474)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
	at dalvik.system.NativeStart.main(Native Method)
~~~

User comment:

>pressed back from map view

This was on Android 4.3 on a Galaxy S2 Skyrocket (SGH-I727).

**Comment by barbeau** [comment]
It looks like the user selected "View route on map", and the vehicles began to load, but then the user hit back before the load completed.  When the load completed, the vehicle overlay tried to initialize itself in BaseMapFragment at line 322 with a call to `getActivity()` to the context:

~~~
public void setupVehicleOverlay() {
        if (mVehicleOverlay == null) {
            mVehicleOverlay = new VehicleOverlay(getActivity(), mMap);
        }
    }
~~~

However, at this point the activity was already destroyed, which resulted in null being passed into VehicleOverlay.

We should do a null check on `getActivity()` here before initializing the vehicle overlay.
