### ISSUE TITLE
NPE when trying to load stops and use "Sort by"

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#390]
Reported by user, stack trace from Developer Console:

>Repro with 3rd & Cedar se bound stop. Spinning cursor, no buses shown, click menu icon on right of app toolbar.

~~~
java.lang.NullPointerException
	at org.onebusaway.android.ui.ArrivalsListFragment.refreshLocal(ArrivalsListFragment.java:1316)
	at org.onebusaway.android.ui.ArrivalsListFragment.doSortBy(ArrivalsListFragment.java:1047)
	at org.onebusaway.android.ui.ArrivalsListFragment.onOptionsItemSelected(ArrivalsListFragment.java:551)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1897)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2046)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
	at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
	at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:541)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4247)
	at android.view.View$PerformClick.run(View.java:17728)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
	at dalvik.system.NativeStart.main(Native Method)
~~~

I believe this is a separate issue from https://github.com/OneBusAway/onebusaway-android/issues/389, as it seems to occur upon refresh, not upon initial load.

**Comment by barbeau** [comment]
Despite referencing a different line number, it does look like this is caused by the same underlying issue as #389.
