### ISSUE TITLE
Crash when restoring old backup in new version of app database

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#473]
**Summary:** 

The app crashes when trying to restore a backup created with an older version of the app/database:

~~~
Process: com.joulespersecond.seattlebusbot, PID: 24120
                                                   java.lang.RuntimeException: Unable to create application org.onebusaway.android.app.Application: android.database.sqlite.SQLiteException: Can't downgrade database from version 23 to 22
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 23 to 22
                                                       at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
                                                       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                       at org.onebusaway.android.provider.ObaProvider.getDatabase(ObaProvider.java:942)
                                                       at org.onebusaway.android.provider.ObaProvider.query(ObaProvider.java:517)
                                                       at android.content.ContentProvider.query(ContentProvider.java:1017)
                                                       at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
                                                       at android.content.ContentResolver.query(ContentResolver.java:498)
                                                       at android.content.ContentResolver.query(ContentResolver.java:441)
                                                       at org.onebusaway.android.provider.ObaContract$Regions.get(ObaContract.java:1054)
                                                       at org.onebusaway.android.provider.ObaContract$Regions.get(ObaContract.java:1035)
                                                       at org.onebusaway.android.app.Application.initObaRegion(Application.java:420)
                                                       at org.onebusaway.android.app.Application.onCreate(Application.java:96)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4795)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5525) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
~~~

**Steps to reproduce:** 

1.  Install an old version of the app with an old version of the database
2.  Star a stop
3.  Go to "Settings->Save to storage"
4.  Update to the app to a new version that includes a new version of the database
5.  Go to "Settings->Restore from storage"

**Expected behavior:** 

Successfully restore the old data and operate as normal.

**Observed behavior:** 

App crashes on startup and is no longer usable.

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Comment by barbeau** [comment]
We aren't currently overriding `onDowngrade()` in `ObaProvider`, and a crash is the default Android behavior in this scenario if this method isn't overridden.  I think we can just override `onDowngrade()` and make sure we execute the SQL queries to update the database schema to the newest version.  Going to give this a shot.

**Comment by barbeau** [comment]
I should add that this bug has probably existed for a very long time - doesn't seem to be related to any recent work.

**Comment by barbeau** [comment]
Calling `onUpgrade()` with the new version number from `onDowngrade()` seems to work - it seems to update the schema correctly.  Interestingly, from some testing with older version numbers, it seems that it can also execute the SQL statements such as "CREATE TABLE..." when that table already exists without crashing.  I would have expected us to need to change the SQL statements to "CREATE TABLE IF NOT EXISTS..." to prevent a crash - maybe this is a change in underlying Android SQLite behavior?

At any rate, we should be able to call this fixed for now.
