### ISSUE TITLE
Route favorite dialog crashes upon orientation change

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#480]
**Summary:** 

Reported via Android Developer Console:

~~~
java.lang.NullPointerException: Attempt to invoke interface method 'void org.onebusaway.android.ui.RouteFavoriteDialogFragment$Callback.onSelectionComplete(boolean)' on a null object reference
	at org.onebusaway.android.ui.RouteFavoriteDialogFragment$1.onClick(RouteFavoriteDialogFragment.java:207)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5438)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
~~~

**Steps to reproduce:** 

I was able to reproduce by doing the following:

1. Open any stop
2. Tap on any arrival
3. Select "Add star to route"
4. Rotate the screen
5. Tap on "Save"

**Expected behavior:** 

The app should complete the rotation and allow the user to save the favorite route.

**Observed behavior:** 

The app crashes with the above stacktrace.

**Device and Android version:** 

I reproduced this on a stock LG G4 with Android 6.0

**Comment by barbeau** [comment]
@cagryInside Could you please take a look at this?
