### ISSUE TITLE
NPE when changing screen orientations in HomeActivity in route mode w/ interruption

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#518]
**Summary:** 

NPE when changing screen orientations in HomeActivity, showing the route, after I received an incoming phone call and returned to the app:

~~~
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.joulespersecond.seattlebusbot, PID: 28657
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
        at org.onebusaway.android.util.UIUtils.isConnected(UIUtils.java:543)
        at org.onebusaway.android.util.UIUtils.getMapErrorString(UIUtils.java:518)
        at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.showMapError(BaseMapFragment.java:604)
        at org.onebusaway.android.map.RouteMapController$RouteLoaderListener.onLoadFinished(RouteMapController.java:398)
        at org.onebusaway.android.map.RouteMapController$RouteLoaderListener.onLoadComplete(RouteMapController.java:435)
        at org.onebusaway.android.map.RouteMapController$RouteLoaderListener.onLoadComplete(RouteMapController.java:382)
        at android.support.v4.content.Loader.deliverResult(Loader.java:126)
        at org.onebusaway.android.map.RouteMapController$RoutesLoader.deliverResult(RouteMapController.java:373)
        at org.onebusaway.android.map.RouteMapController$RoutesLoader.deliverResult(RouteMapController.java:345)
        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
        at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
~~~

**Steps to reproduce:** 

I saw this while trying to grab screenshots for https://github.com/OneBusAway/onebusaway-android/issues/517.

Steps were something along the lines of:

1. Tap on a stop on the map in portrait orientation
1. Tap on an arrival time, and choose "Show route on map"
1. Close the sliding panel by hitting the Back button
1. Rotate the device to landscape orientation

I then got an incoming phone call and answered it, and then returned to OBA.  At this point it crashed and I grabbed the above stack trace via Android Studio.

**Expected behavior:** 

Show me the route on the map.

**Observed behavior:** 

It crashed.

**Device and Android version:** 

Stock LG G4 w/ Android 6.0 and Google Play Services v9.0.83 on the device.

**Screenshots:** 

N/A

**Comment by barbeau** [comment]
Similar stack trace from a user w/ 2.0.12 installed, but for the VehicleLoader instead of the RouteLoader:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at org.onebusaway.android.util.UIUtils.isConnected(UIUtils.java:544)
	at org.onebusaway.android.util.UIUtils.getMapErrorString(UIUtils.java:518)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.showMapError(BaseMapFragment.java:605)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadFinished(RouteMapController.java:493)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadComplete(RouteMapController.java:524)
	at org.onebusaway.android.map.RouteMapController$VehicleLoaderListener.onLoadComplete(RouteMapController.java:475)
	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	at org.onebusaway.android.map.RouteMapController$VehiclesLoader.deliverResult(RouteMapController.java:466)
	at org.onebusaway.android.map.RouteMapController$VehiclesLoader.deliverResult(RouteMapController.java:439)
	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
~~~

Device:

~~~
Galaxy S7 Edge (hero2qlteatt)
Manufacturer Samsung 
Android version Android 6.0 
RAM (MB) 4096 
Screen size 1440 × 2560 
Screen density (dpi) 640 
OpenGL ES version 3.1 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8996
~~~

**Comment by barbeau** [comment]
The Android docs show using the Application context instead of Activity context for Toasts:
https://developer.android.com/guide/topics/ui/notifiers/toasts.html#Basics

...which seems to make sense to me, so that's what I'm doing in https://github.com/OneBusAway/onebusaway-android/commit/7ac161d6d5f0b3760f1fa66c512f9dbc512e985d.
