### ISSUE TITLE
NPE when getting Location in Send Feedback flow

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#530]
**Summary:** 

From Android Developer Console for staged rollout v2.0.12:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
	at org.onebusaway.android.ui.HomeActivity.goToSendFeedBack(HomeActivity.java:1054)
	at org.onebusaway.android.ui.HomeActivity.goToNavDrawerItem(HomeActivity.java:411)
	at org.onebusaway.android.ui.HomeActivity.onNavigationDrawerItemSelected(HomeActivity.java:355)
	at org.onebusaway.android.ui.NavigationDrawerFragment.selectItem(NavigationDrawerFragment.java:263)
	at org.onebusaway.android.ui.NavigationDrawerFragment$3.onClick(NavigationDrawerFragment.java:430)
	at android.view.View.performClick(View.java:5197)
	at android.view.View$PerformClick.run(View.java:20926)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
~~~

User comment:

>Upgrade is terrible. No improvements, more confusing, can't turn off hints/help, crashes. Appears there was no testing by actual users.

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

~~~
Galaxy S4 (jfltevzw)
Manufacturer Samsung 
Android version Android 4.2 
RAM (MB) 2048 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model APQ8064
~~~

@cagryInside Could you please take a look?  Thanks!

**Comment by cagryInside** [comment]
To reproduce this problem:

1. Disable location services in your phone
2. Restart your phone
3. Open OBA and go to `send feedback`
