### ISSUE TITLE
NPEs when clicking a bus stop and changing screen orientation at the same time in HomeActivity 

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#533]
**Summary:** 

Getting following NPEs when clicking a bus stop and just after changing the screen orientation in `HomeActivity`:

**Issue 1:**

```
 FATAL EXCEPTION: main
                                                                                   java.lang.NullPointerException
at org.onebusaway.android.ui.HomeActivity$6.onPanelSlide(HomeActivity.java:1322)
at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchOnPanelSlide(SlidingUpPanelLayout.java:631)
at com.sothree.slidinguppanel.SlidingUpPanelLayout.onPanelDragged(SlidingUpPanelLayout.java:1154)
at com.sothree.slidinguppanel.SlidingUpPanelLayout.access$900(SlidingUpPanelLayout.java:29)
SlidingUpPanelLayout.java:1384)
at com.sothree.slidinguppanel.ViewDragHelper.continueSettling(ViewDragHelper.java:735)
at com.sothree.slidinguppanel.SlidingUpPanelLayout.computeScroll(SlidingUpPanelLayout.java:1231)
at android.view.View.getDisplayList(View.java:10444)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
at android.view.View.getDisplayList(View.java:10418)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:879)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:1955)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1661)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2505)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:4945)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
```

**Issue 2:**

```
Process: com.joulespersecond.seattlebusbot, PID: 
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
  at org.onebusaway.android.provider.ObaContract$RouteHeadsignFavorites.isFavorite(ObaContract.java:1395)
 at org.onebusaway.android.ui.ArrivalInfo.<init>(ArrivalInfo.java:249)
 at org.onebusaway.android.ui.ArrivalInfo.convertObaArrivalInfo(ArrivalInfo.java:75)
 at org.onebusaway.android.ui.ArrivalsListFragment.getArrivalInfo(ArrivalsListFragment.java:868)
 at org.onebusaway.android.ui.ArrivalsListHeader.refreshArrivalInfoData(ArrivalsListHeader.java:648)
 at org.onebusaway.android.ui.ArrivalsListHeader.refresh(ArrivalsListHeader.java:624)
 at org.onebusaway.android.ui.HomeActivity$6.onPanelCollapsed(HomeActivity.java:1352)
 at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchOnPanelCollapsed(SlidingUpPanelLayout.java:644)
at com.sothree.slidinguppanel.SlidingUpPanelLayout$DragHelperCallback.onViewDragStateChanged(SlidingUpPanelLayout.java:1363)
at com.sothree.slidinguppanel.ViewDragHelper.setDragState(ViewDragHelper.java:873)
at com.sothree.slidinguppanel.ViewDragHelper$2.run(ViewDragHelper.java:336)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Steps to reproduce:** 
1. In `HomeActivity` click on a bus stop icon
2. Rotate the screen very fast just before `ArrivalsListLoader` has been finished

**Expected behavior:** 

Not crash

**Observed behavior:** 

It crashed.

**Device and Android version:** 

Issue 1 was observed with:
HTC EVO 3D w/ Android v4.*

Issue 2 was observed with:
Motorola Nexus 6 w/ Android 6.0.1

**Comment by amrhossamdev** [comment]
This was fixed.
