### ISSUE TITLE
NPE tapping on arrival time - ObaReferences.getRoute(java.lang.String)

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#571]
**Summary:** 

From Android Developer Console for v2.0.13:

~~~
java.lang.NullPointerException: Attempt to invoke interface method 'org.onebusaway.android.io.elements.ObaRoute org.onebusaway.android.io.elements.ObaReferences.getRoute(java.lang.String)' on a null object reference
	at org.onebusaway.android.ui.ArrivalsListFragment$1.onClick(ArrivalsListFragment.java:737)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1019)
	at android.widget.AdapterView.performItemClick(AdapterView.java:334)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3667)
	at android.widget.AbsListView$3.run(AbsListView.java:5590)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
~~~

Looks like this happens when trying to report an arrival time problems after tapping on an arrival time.

**Steps to reproduce:** 

Unknown (involves tapping on arrival time, and then tapping "Report arrival time problem")

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

~~~
Galaxy S4 (jflterefreshspr)
Manufacturer Samsung 
Android version Android 4.2 
RAM (MB) 2048 
Screen size 1080 × 1920
Screen density (dpi) 480 
OpenGL ES version 2.0 
Native platform armeabi-v7a
CPU make Qualcomm
CPU model APQ8064
~~~

**Comment by barbeau** [comment]
@cagryInside Could you please take a shot at this one?  If we don't need agencyName, we can just not pass it to the problem reporting activity/fragment if the references object is null.
