### ISSUE TITLE
NPE in SlidingUpPanelLayout$SavedState.writeToParcel()

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#580]
**Summary:** 

From Android Developer Console for v2.0.14:

~~~
java.lang.NullPointerException
	at com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState.writeToParcel(SlidingUpPanelLayout.java:1491)
	at android.os.Parcel.writeParcelable(Parcel.java:1254)
	at android.os.Parcel.writeValue(Parcel.java:1173)
	at android.os.Parcel.writeSparseArray(Parcel.java:662)
	at android.os.Parcel.writeValue(Parcel.java:1198)
	at android.os.Parcel.writeMapInternal(Parcel.java:591)
	at android.os.Bundle.writeToParcel(Bundle.java:1619)
	at android.os.Parcel.writeBundle(Parcel.java:605)
	at android.os.Parcel.writeValue(Parcel.java:1170)
	at android.os.Parcel.writeMapInternal(Parcel.java:591)
	at android.os.Bundle.writeToParcel(Bundle.java:1619)
	at android.os.Parcel.writeBundle(Parcel.java:605)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2213)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:2877)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4777)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:765)
	at dalvik.system.NativeStart.main(Native Method)
~~~

Looks like this is an issue in the SlidingUpPanel library.

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

~~~
Device
Galaxy Prevail2 (raybst)
Manufacturer Samsung 
Android version Android 4.1 
RAM (MB) 1024 
Screen size 480 × 800 
Screen density (dpi) 240 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8655
~~~

**Comment by barbeau** [comment]
Closing this as "Won't fix" as it's not an OBA issue, but I still wanted to document the stack trace in case this becomes more frequent (currently only 1 report).
