### ISSUE TITLE
IllegalStateException - Map size can't be 0

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#581]
**Summary:** 

From Android Developer Console for v2.0.14:

~~~
java.lang.IllegalStateException: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
	at maps.f.g.b(Unknown Source)
	at maps.E.a.a(Unknown Source)
	at maps.af.k$2.a(Unknown Source)
	at maps.E.a.a(Unknown Source)
	at maps.af.t.b(Unknown Source)
	at vl.onTransact(:com.google.android.gms.DynamiteModulesB:92)
	at android.os.Binder.transact(Binder.java:380)
	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.animateCamera(Unknown Source)
	at com.google.android.gms.maps.GoogleMap.animateCamera(Unknown Source)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.zoomToRegion(BaseMapFragment.java:606)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment$MapDialogFragment$2.onClick(BaseMapFragment.java:960)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:153)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
~~~

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

~~~
Moto X (1st Gen) (ghost)
Manufacturer Motorola 
Android version Android 4.2 
RAM (MB) 2048 
Screen size 720 × 1280 
Screen density (dpi) 320 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8960
~~~

**Comment by barbeau** [comment]
Best solution seems to be to follow suggestion in stacktrace for using `newLatLngBounds(LatLngBounds, int, int, int)`:

>Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.

See http://stackoverflow.com/a/30497039/937715.

**Comment by therajanmaurya** [comment]
Hi @barbeau,

```java
 public void zoomToRegion() {
        // If we have a region, then zoom to it.
        ObaRegion region = Application.get().getCurrentRegion();

        if (region != null && mMap != null) {
            LatLngBounds b = MapHelpV2.getRegionBounds(region);

            //Setting the width and height of your screen
            int width = getResources().getDisplayMetrics().widthPixels;
            int height = getResources().getDisplayMetrics().heightPixels;
            int padding = (int) (width * 0.12); // offset from edges of the map 12% of screen

            mMap.animateCamera((CameraUpdateFactory.newLatLngBounds(b, width, height, padding)));
        }
    }
```

We are good with this.

**Comment by barbeau** [comment]
Ok, great - can you please put into a pull request?
