### ISSUE TITLE
Trip Planning NumberFormatException on time Spanish language

### ISSUE THREAD

**Issue by themonki** [OneBusAway/onebusaway-android#605]
**Summary:** 

On trip planning using **Spanish (Colombia)** the format on the time option cause error:

11:44a. m.

on English show

11:44 AM

Developer console
```
07-19 11:44:15.131 21399-21399/com.mio.onebusaway D/HomeActivity: onOptionsItemSelected
07-19 11:44:16.435 21399-21399/com.mio.onebusaway I/Timeline: Timeline: Activity_launch_request id:com.mio.onebusaway time:10677696
07-19 11:44:16.449 21399-21453/com.mio.onebusaway I/GAv4: Dry run enabled. Would have sent hit: ht=1468946656449, _v=ma9.0.80, a=1313784130, aid=com.mio.onebusaway, an=OneBusAway MIO, av=2.0.16, cd=HomeActivity, cd1=MIO (CALI-CO), cid=b822d2e9-be05-449d-aa96-360a50314ea0, ea=button_press, ec=ui_action, el=Clicked Trip Plan Link, sr=720x1184, t=event, tid=UA-XXXXXXX-XX, ul=es-co, v=1
07-19 11:44:16.450 21399-21453/com.mio.onebusaway I/GAv4: Dry run enabled. Would have sent hit: ht=1468946656449, _v=ma9.0.80, a=1743622245, aid=com.mio.onebusaway, an=OneBusAway MIO, av=2.0.16, cd=HomeActivity, cd1=MIO (CALI-CO), cid=b822d2e9-be05-449d-aa96-360a50314ea0, ea=button_press, ec=ui_action, el=Clicked Trip Plan Link, sr=720x1184, t=event, tid=UA-YYYYYYY-YY, ul=es-co, v=1
07-19 11:44:16.753 21399-21399/com.mio.onebusaway D/LocationServicesCallback: GoogleApiClient.onConnected
07-19 11:44:16.810 21399-21399/com.mio.onebusaway I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@4db619f time:10678072
07-19 11:44:16.955 21399-21399/com.mio.onebusaway D/NavDrawerFragment: Saving position = 0
07-19 11:44:25.018 21399-21399/com.mio.onebusaway I/DateUtils: 11:44a. m. didn't parse
                                                               java.lang.NumberFormatException: Invalid int: "44A. M."
                                                                   at java.lang.Integer.invalidInt(Integer.java:138)
                                                                   at java.lang.Integer.parse(Integer.java:410)
                                                                   at java.lang.Integer.parseInt(Integer.java:367)
                                                                   at java.lang.Integer.parseInt(Integer.java:334)
                                                                   at org.opentripplanner.util.DateUtils.secondsPastMidnight(DateUtils.java:179)
                                                                   at org.opentripplanner.util.DateUtils.secPastMid(DateUtils.java:129)
                                                                   at org.opentripplanner.util.DateUtils.toDate(DateUtils.java:45)
                                                                   at org.opentripplanner.api.ws.Request.setDateTime(Request.java:263)
                                                                   at org.onebusaway.android.directions.util.TripRequestBuilder.execute(TripRequestBuilder.java:237)
                                                                   at org.onebusaway.android.ui.TripPlanActivity.route(TripPlanActivity.java:253)
                                                                   at org.onebusaway.android.ui.TripPlanFragment.checkRequestAndSubmit(TripPlanFragment.java:222)
                                                                   at org.onebusaway.android.ui.TripPlanFragment.access$200(TripPlanFragment.java:71)
                                                                   at org.onebusaway.android.ui.TripPlanFragment$6.onClick(TripPlanFragment.java:200)
                                                                   at android.view.View.performClick(View.java:5280)
                                                                   at android.view.View$PerformClick.run(View.java:21239)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:224)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-19 11:44:25.024 21399-21526/com.mio.onebusaway D/TripRequest: URL: http://172.16.1.55:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=3,46890,-76,5226&time=11:44a. m.&fromPlace=3,46890,-76,5226&date=07-19-2016&optimize=QUICK&arriveBy=false
07-19 11:44:25.221 21399-21526/com.mio.onebusaway E/TripRequest: Error fetching JSON or XML: java.io.FileNotFoundException: http://172.16.1.55:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=3,46890,-76,5226&time=11:44a. m.&fromPlace=3,46890,-76,5226&date=07-19-2016&optimize=QUICK&arriveBy=false
07-19 11:44:25.221 21399-21526/com.mio.onebusaway W/System.err: java.io.FileNotFoundException: http://172.16.1.55:8080/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=3,46890,-76,5226&time=11:44a. m.&fromPlace=3,46890,-76,5226&date=07-19-2016&optimize=QUICK&arriveBy=false
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.requestPlan(TripRequest.java:174)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.doInBackground(TripRequest.java:91)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.doInBackground(TripRequest.java:46)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-19 11:44:25.227 21399-21526/com.mio.onebusaway W/System.err:     at java.lang.Thread.run(Thread.java:818)
07-19 11:44:25.231 21399-21399/com.mio.onebusaway I/Timeline: Timeline: Activity_launch_request id:com.mio.onebusaway time:10686492
07-19 11:44:35.284 21399-21524/com.mio.onebusaway V/RenderScript: 0x95be6000 Launching thread(s), CPUs 4
```

**Steps to reproduce:** 

1. Set divice to spanish languaje
2. Go to Trip Planning
3. Select destiny

**Expected behavior:** 

Show the result of trips

**Observed behavior:** 

Show message *Planning not possible*

**Device and Android version:** 

Xperia Z3 Compact (D5803)
Manufacturer Sony 
Android version Android 6.0.1
RAM (MB) 2048 
Screen size 720 × 1280 
Screen density (dpi) 320 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974AC
Google Play Services 9.0.83

**Screenshots:** 

Spanish

![image](https://cloud.githubusercontent.com/assets/1817333/16958714/4ffd67e6-4da7-11e6-8adf-e510a1f3fe91.png)

![image](https://cloud.githubusercontent.com/assets/1817333/16958709/4961c544-4da7-11e6-8f79-7877f69bbb3f.png)

English

![image](https://cloud.githubusercontent.com/assets/1817333/16958818/ca2e2ca8-4da7-11e6-9c16-8449bda173c6.png)

![image](https://cloud.githubusercontent.com/assets/1817333/16958833/d9c880a0-4da7-11e6-922b-e914f4c6a69b.png)

**Comment by barbeau** [comment]
Thanks @themonki!  On a related note, would you be able to do a Spanish translation of the text added in #602?

@sdjacobs could you take a shot at this bug?

**Comment by themonki** [comment]
@barbeau I will review

**Comment by barbeau** [comment]
@themonki This issue should now be fixed in `master` branch - could you please test again and make sure it works?

**Comment by themonki** [comment]
@barbeau I confirm this is fixed with current master.

I will try to get the translations soon.

**Comment by barbeau** [comment]
Thanks!
