### ISSUE TITLE
Trip planning - NPE while using custom api urls

### ISSUE THREAD

**Issue by cagryInside** [OneBusAway/onebusaway-android#635]
**Summary:** 

We are getting NPE when using a custom api url.

```

java.lang.RuntimeException: Unable to resume activity {com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.onebusaway.android.io.elements.ObaRegion.getOtpBaseUrl()' on a null object reference
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
   at android.app.ActivityThread.-wrap11(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.onebusaway.android.io.elements.ObaRegion.getOtpBaseUrl()' on a null object reference
   at org.onebusaway.android.ui.PreferencesActivity.onResume(PreferencesActivity.java:165)
   at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
   at android.app.Activity.performResume(Activity.java:6327)
   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
   at android.app.ActivityThread.-wrap11(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Steps to reproduce:** 

1. Go to `Settings`
1. Set custom api url
1. Go to main screen
1. Tap on `Settings` again

**Expected behavior:** 

No NPE

**Observed behavior:** 

NPE

**Device and Android version:** 

Motorola Nexus 6 w/ Android 6.0.1

**Screenshots:** 
N/A

**Comment by cagryInside** [comment]
@barbeau I am tackling with this.

**Comment by themonki** [comment]
I see this issue too on release 2.1.1

**Comment by barbeau** [comment]
Thanks @cagryInside!  Yes, this is cleanup we missed related to implementing trip planning.

**Comment by cagryInside** [comment]
@barbeau Just opened a PR. Should be good now.

**Comment by barbeau** [comment]
I'll try to get a bug fix release at least into beta before the end of the week so the custom API is functional on a release.
