### ISSUE TITLE
IllegalArgumentException when dismissing region dialog

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#641]
**Summary:** 

From Android Developer Console for v2.1.1:

~~~
java.lang.IllegalArgumentException: View not attached to window manager
	at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:378)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:223)
	at android.view.Window$LocalWindowManager.removeView(Window.java:432)
	at android.app.Dialog.dismissDialog(Dialog.java:278)
	at android.app.Dialog.access$000(Dialog.java:71)
	at android.app.Dialog$1.run(Dialog.java:111)
	at android.app.Dialog.dismiss(Dialog.java:268)
	at org.onebusaway.android.region.ObaRegionsTask.onPostExecute(ObaRegionsTask.java:151)
	at org.onebusaway.android.region.ObaRegionsTask.onPostExecute(ObaRegionsTask.java:53)
	at android.os.AsyncTask.finish(AsyncTask.java:417)
	at android.os.AsyncTask.access$300(AsyncTask.java:127)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3687)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
~~~

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

~~~
Manufacturer Samsung 
Android version Android 2.1 
RAM (MB) 128 
Screen size 800 × 480 
Screen density (dpi) 240 
OpenGL ES version 2.0 
Native platform armeabi-v7a 
CPU make — 
CPU model —
~~~

Interestingly, Google Play labels the Android version for this device as "Android 2.3.3 - 2.3.7", but the device details reports it as Android 2.1 above.

**Comment by barbeau** [comment]
I'm going to chalk this up to a Gingerbread issue so I'm marking as "Won't fix".  We are already checking a number of things to make sure we're not trying to dismiss the dialog outside of the activity lifecycle, including checking `mProgressDialog.isShowing()`, and using `UIUtils.canManageDialog()`, which checks `!activity.isFinishing() && !activity.isDestroyed()`.  I'm assuming Gingerbread reported a stale value for one of these, or execution was delayed significantly which resulted in the state changing by the time the dialog was dismissed.  We really can't do much about this.
