### ISSUE TITLE
Custom https OTP URLs don't work if "https://" is omitted

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#661]
**Summary:** 

Assuming https://github.com/OneBusAway/onebusaway-android/pull/644 is merged (I saw this while testing, which doesn't need to block merge of https://github.com/OneBusAway/onebusaway-android/pull/644, but I wanted to capture info for later)

If you enter "maps.usf.edu/otp" as a custom OTP API, you'll see the following stack trace when trying to plan a trip:

~~~
D/TripRequest: URL: http://maps.usf.edu/otp/routers/default/plan?wheelchair=false&showIntermediateStops=true&toPlace=28.0659,-82.4301&time=02:21PM&fromPlace=27.9552,-82.4584&date=08-10-2016&optimize=QUICK&arriveBy=false
E/TripRequest: Error fetching JSON or XML: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
                                                                                 at [Source: buffer(com.android.okhttp.internal.http.HttpConnection$FixedLengthSource@62236d2).inputStream(); line: 1, column: 1]
W/System.err: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
W/System.err:  at [Source: buffer(com.android.okhttp.internal.http.HttpConnection$FixedLengthSource@62236d2).inputStream(); line: 1, column: 1]
W/System.err:     at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:381)
W/System.err:     at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1494)
W/System.err:     at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1102)
W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.requestPlan(TripRequest.java:177)
W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.doInBackground(TripRequest.java:94)
W/System.err:     at org.onebusaway.android.directions.tasks.TripRequest.doInBackground(TripRequest.java:48)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
~~~

Workaround - enter the full URL - "https://maps.usf.edu/otp".

In the near future all OBA/OTP URLs will need to be HTTPS to work on iOS, so we should allow users to enter partial HTTPS URLs as well.

**Steps to reproduce:** 

1. Enter a custom OTP API of `maps.usf.edu/otp`
1. Plan a trip in Tampa

**Expected behavior:** 

Successfully plan a trip

**Observed behavior:** 

Crash with the above stack trace

**Device and Android version:** 

Stock LG G4 w/ Android 6.0

**Comment by bmander** [comment]
Closing as fixed. A user-entered custom OTP URL without a scheme is now normalized before the request. In `directions/util/TripRequestBuilder.kt`, the user's custom URL preference flows into `otpTarget.baseUrl`, and `formattedOtpBaseUrl` (lines ~250-261) attempts `URL(otpBaseUrl)` and, on `MalformedURLException` (missing scheme), prepends the https prefix before formatting via `RegionUtils.formatOtpBaseUrl`. So entering e.g. `maps.usf.edu/otp` — the exact case reported here — is treated as `https://maps.usf.edu/otp` rather than failing to parse.
