### ISSUE TITLE
NPE when adding/updating stop in database

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#669]
**Summary:** 

This is a long-standing but infrequently occurring bug that I've seen since v1.x, and has occurred most recently in v2.1.2 (staged rollout):

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
	at org.onebusaway.android.provider.ObaContract$Stops.insertOrUpdate(ObaContract.java:533)
	at org.onebusaway.android.ui.ArrivalsListFragment.addToDB(ArrivalsListFragment.java:1507)
	at org.onebusaway.android.ui.ArrivalsListFragment.onLoadFinished(ArrivalsListFragment.java:435)
	at org.onebusaway.android.ui.ArrivalsListFragment.onLoadFinished(ArrivalsListFragment.java:89)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.reportStart(LoaderManager.java:315)
	at android.support.v4.app.LoaderManagerImpl.doReportStart(LoaderManager.java:819)
	at android.support.v4.app.Fragment.performStart(Fragment.java:2009)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
~~~

**Steps to reproduce:** 

Unknown - user comments:

>* adding star to route from list of routes at a stop crashes it
* it radumbly stopped working
* app crashed when trying to filter route info at a stop

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

A variety of devices, including:
* Galaxy S5 (kltetmo)
* Galaxy J1 (j1xlteaio)
* Galaxy S7 (heroqltetfnvzw)
* HTC One (m7)
* Moto X Pure Edition (clark)

...and a variety of Android versions, including 5.0, 5.1, and 6.0.

**Comment by barbeau** [comment]
It looks like this is a case of the arrival times Loader finishing, and the Fragment trying to update the local database after it has been detached from the Activity - therefore, passing in the Activity context to `ObaContract.insertOrUpdate()` results in an NPE when trying to retrieve the `ContentResolver` via `context.getContentResolver();`.

Possible solutions are to use the Application context here instead of the Activity context, or just don't update the database if the fragment has been detached.

**Comment by barbeau** [comment]
From https://developer.android.com/guide/topics/providers/content-providers.html:

>When you want to access data in a content provider, you use the ContentResolver object in your application's Context to communicate with the provider as a client.

So it sounds like we should be safe using the Application context.
