### ISSUE TITLE
NPE when accessing route favorite in database

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#673]
**Summary:** 

From Android Developer Console for v2.1.1 and v2.0.14:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
	at org.onebusaway.android.provider.ObaContract$RouteHeadsignFavorites.isFavorite(ObaContract.java:1415)
	at org.onebusaway.android.ui.ArrivalInfo.<init>(ArrivalInfo.java:249)
	at org.onebusaway.android.ui.ArrivalInfo.convertObaArrivalInfo(ArrivalInfo.java:65)
	at org.onebusaway.android.ui.ArrivalsListFragment.getArrivalInfo(ArrivalsListFragment.java:841)
	at org.onebusaway.android.ui.ArrivalsListHeader.refreshArrivalInfoData(ArrivalsListHeader.java:648)
	at org.onebusaway.android.ui.ArrivalsListHeader.refresh(ArrivalsListHeader.java:624)
	at org.onebusaway.android.ui.HomeActivity$7.onPanelCollapsed(HomeActivity.java:1400)
	at org.onebusaway.android.ui.HomeActivity$7.onPanelStateChanged(HomeActivity.java:1359)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchOnPanelStateChanged(SlidingUpPanelLayout.java:644)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.setPanelStateInternal(SlidingUpPanelLayout.java:1108)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.access$900(SlidingUpPanelLayout.java:32)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout$DragHelperCallback.onViewDragStateChanged(SlidingUpPanelLayout.java:1340)
	at com.sothree.slidinguppanel.ViewDragHelper.setDragState(ViewDragHelper.java:911)
	at com.sothree.slidinguppanel.ViewDragHelper$2.run(ViewDragHelper.java:336)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
~~~

**Steps to reproduce:** 

Unknown

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

Variety of devices, including:

* OnePlus One (A0001)
* Galaxy Grand Prime (gprimeltetmo)
* LG G4 (p1)

Variety of Android versions, including:

* Android 6.0
* Android 5.1

**Comment by barbeau** [comment]
Likely same root cause as https://github.com/OneBusAway/onebusaway-android/issues/669 - trying to access the Activity context after the fragment has been detached from the Activity.

We should probably review all contexts being passed into the `ObaContract` methods to see if this can happen elsewhere as well.

**Comment by barbeau** [comment]
From https://developer.android.com/guide/topics/providers/content-providers.html:

>When you want to access data in a content provider, you use the ContentResolver object in your application's Context to communicate with the provider as a client.

So it sounds like we should be safe using the Application context.
