### ISSUE TITLE
IllegalArgumentException when loading arrivals for trips with null headsigns

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#690]
**Summary:** 

If you tap on a stop that has a trip with a null headsign, you get a crash with below stack trace:

~~~
 Process: com.joulespersecond.seattlebusbot, PID: 3860
 java.lang.IllegalArgumentException: the bind value at index 2 is null
	 at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
	 at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
	 at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	 at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1426)
	 at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
	 at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:333)
	 at org.onebusaway.android.provider.ObaProvider.queryInternal(ObaProvider.java:866)
	 at org.onebusaway.android.provider.ObaProvider.query(ObaProvider.java:589)
	 at android.content.ContentProvider.query(ContentProvider.java:1017)
	 at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
	 at android.content.ContentResolver.query(ContentResolver.java:498)
	 at android.content.ContentResolver.query(ContentResolver.java:441)
	 at org.onebusaway.android.provider.ObaContract$RouteHeadsignFavorites.isFavorite(ObaContract.java:1418)
	 at org.onebusaway.android.ui.ArrivalInfo.<init>(ArrivalInfo.java:248)
	 at org.onebusaway.android.ui.ArrivalInfo.convertObaArrivalInfo(ArrivalInfo.java:75)
	 at org.onebusaway.android.ui.ArrivalsListAdapterStyleA.setData(ArrivalsListAdapterStyleA.java:53)
	 at org.onebusaway.android.ui.ArrivalsListFragment.setResponseData(ArrivalsListFragment.java:546)
	 at org.onebusaway.android.ui.ArrivalsListFragment.onLoadFinished(ArrivalsListFragment.java:459)
	 at org.onebusaway.android.ui.ArrivalsListFragment.onLoadFinished(ArrivalsListFragment.java:89)
	 at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
	 at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
	 at android.support.v4.content.Loader.deliverResult(Loader.java:126)
	 at org.onebusaway.android.ui.ArrivalsListLoader.deliverResult(ArrivalsListLoader.java:59)
	 at org.onebusaway.android.ui.ArrivalsListLoader.deliverResult(ArrivalsListLoader.java:27)
	 at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
	 at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
	 at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
	 at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
	 at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:148)
	 at android.app.ActivityThread.main(ActivityThread.java:5525)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
~~~

It's rare for trip headsigns to be null but it apparently happens in Puget Sound and RVTD occasionally - this trip seems to be the problem at RVTD stop_code 610030 (http://oba.rvtd.org:8080/onebusaway-api-webapp/api/where/arrivals-and-departures-for-stop/1739_b18f3200-6bc5-475b-ac91-c6b06d47d124.json?minutesAfter=65&app_ver=70&version=2&key=v1_BktoDJ2gJlu6nLM6LsT9H8IUbWc%3DcGF1bGN3YXR0c0BnbWFpbC5jb20%3D):

~~~
trips: [
{
blockId: "1739_null",
directionId: "0",
id: "1739_0aac7fc5-01c2-4686-b509-0d25fc0f0c53",
routeId: "1739_72415cec-22c1-4514-be5d-b29f06d6d180",
routeShortName: "",
serviceId: "1739_c626d3e9-e829-4f37-9c36-ef67bcc10a88",
shapeId: "1739_0305bf6c-51ab-4e18-b17e-3d55285d2f0e",
timeZone: "",
tripHeadsign: null,
tripShortName: "61"
},
~~~

**Steps to reproduce:** 

1. Go to Rogue Valley (RVTD)
1. Go to stop_code 610030 (via search or map) and show arrivals for that stop

**Expected behavior:** 

Not crash and show arrivals

**Observed behavior:** 

Crash

**Device and Android version:** 

Reproduced on LG G4 w/ Android 6.0

**Comment by barbeau** [comment]
Null headsigns also prevent the route from being marked as a favorite when starring it.  I'll fix both in the commit for this issue.

**Comment by barbeau** [comment]
Via Android Developer Console crash report a user has reported this that this occurs elsewhere, too (Puget Sound?):

>wont load times for front st station forces self closed

**Comment by aaronbrethorst** [comment]
As it works out, this does crash iOS, too! Thanks for the incredibly detailed repro. I've fixed it and it will land in the next release of the iOS client: https://github.com/OneBusAway/onebusaway-iphone/pull/729
