### ISSUE TITLE
java.io.FileNotFoundException for resource icon on OnePlus One devices

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#711]
**Summary:** 

We've seen a spike in crashes (87 over last week, 126 total over 2 weeks) mostly for OnePlus One devices (111 crashes on OnePlusOne, 3 on Droid Turbo, and 1 on Galaxy S5) with this stack trace:

~~~
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.joulespersecond.seattlebusbot/org.onebusaway.android.ui.HomeActivity}: android.content.res.Resources$NotFoundException: File /data/system/theme/icons/com.joulespersecond.seattlebusbot_7f030000_0.png from drawable resource ID #0x7f030000
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.content.res.Resources$NotFoundException: File /data/system/theme/icons/com.joulespersecond.seattlebusbot_7f030000_0.png from drawable resource ID #0x7f030000
	at android.content.res.Resources.openRawResource(Resources.java:1336)
	at android.content.res.Resources.openRawResource(Resources.java:1306)
	at maps.V.N.a(Unknown Source)
	at maps.D.e.a(Unknown Source)
	at maps.D.p.a(Unknown Source)
	at maps.ad.ae.a(Unknown Source)
	at maps.ad.t.a(Unknown Source)
	at maps.ad.M.a(Unknown Source)
	at wd.onTransact(:com.google.android.gms.DynamiteModulesB:107)
	at android.os.Binder.transact(Binder.java:387)
	at com.google.android.gms.maps.internal.IMapFragmentDelegate$zza$zza.onCreateView(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment$zza.onCreateView(Unknown Source)
	at com.google.android.gms.dynamic.zza$4.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreateView(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
	at org.onebusaway.android.map.googlemapsv2.BaseMapFragment.onCreateView(BaseMapFragment.java:181)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:601)
	at org.onebusaway.android.ui.HomeActivity.onStart(HomeActivity.java:334)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6268)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	... 9 more
Caused by: java.io.FileNotFoundException: /data/system/theme/icons/com.joulespersecond.seattlebusbot_7f030000_0.png
	at android.content.res.AssetManager.openNonAssetNative(Native Method)
	at android.content.res.AssetManager.openNonAsset(AssetManager.java:423)
	at android.content.res.Resources.openRawResource(Resources.java:1333)
	... 36 more
~~~

This doesn't seem to be related to any change by us, as it happened 2 times on app version 70 and 126 times on version 71.

This [StackOverflow issue](http://stackoverflow.com/questions/40109898/location-map-crash-in-oneplus-one-device) points to this [CyanogenMod issue](https://jira.cyanogenmod.org/browse/BACON-5169).  From that issue:

>Changing from the Hexo theme to any other CyanogenMod theme fixes the issue.

I'm going to mark this as "Won't fix", as it seems to be an issue with CyanogenMod.

**Steps to reproduce:** 

Start app on OnePlus One with Hexo theme active

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash with above stacktrace

**Device and Android version:** 

111 crashes on:

~~~
OnePlus One (A0001)
Manufacturer Symphony Teleca
Android version Android 4.3 
RAM (MB) 3072 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974AC
~~~

3 crashes on:

~~~

Droid Turbo (quark)
Manufacturer Motorola
Android version Android 4.4 
RAM (MB) 3000 
Screen size 1440 × 2560 
Screen density (dpi) 640 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model APQ8084
~~~

1 crash on:

~~~

Galaxy S5 (kltetmo)
Manufacturer Samsung 
Android version Android 4.4 
RAM (MB) 2048 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974
~~~

**Screenshots:** 

N/A

**Comment by barbeau** [comment]
I'm going to mark this as "Won't fix", as it seems to be an issue with CyanogenMod Hexo theme.  Changing to another theme on the device fixes the problem, based on the above linked issues.

**Comment by barbeau** [comment]
I've heard back from two users that experienced this bug - neither had Hexo theme enabled.  However, when they switched to a different theme, and then switched back, it seemed to resolve the crash and everything works fine now.  So the simple action of switching themes seems to resolve the issue.
