### ISSUE TITLE
Crash when reporting arrival time problem via ArrivalListFragment

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#729]
**Summary:** 

From Android Developer console:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at android.content.ComponentName.<init>(ComponentName.java:77)
	at android.content.Intent.<init>(Intent.java:4170)
	at org.onebusaway.android.ui.ArrivalsListFragment.makeIntent(ArrivalsListFragment.java:661)
	at org.onebusaway.android.ui.ArrivalsListFragment$1.onClick(ArrivalsListFragment.java:756)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1142)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3872)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3637)
	at android.view.View.dispatchTouchEvent(View.java:8476)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:785)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
	at android.view.View.dispatchPointerEvent(View.java:8671)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5356)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
~~~

**Steps to reproduce:** 

Unknown - maybe rotate phone while dialog is open?

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

LG Leon 4G LTE (c50)
Manufacturer LGE 
Android version Android 5.0 
RAM (MB) 1024 
Screen size 480 × 854 
Screen density (dpi) 240 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8916

**Comment by barbeau** [comment]
I believe this is a bug in the device, as this shouldn't be able to happen.  The user is clicking on an arrival time and then "Report an arrival time problem", and we're getting the current activity the `ArrivalListFragment` is attached to via `getActivity()` so we can start the issue reporting activity.  However, `getActivity()` is returning `null`.  This shouldn't be possible, as the Fragment should only be visible if it's attached to an Activity.  There is only one instance of this report in the console, so I'm closing as "Won't fix" unless more occurrences pop up.
