### ISSUE TITLE
OutOfMemoryError when choosing gallery photo in issue report

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#730]
**Summary:** 

Reported by HART, and via Android Developer Console:

~~~
java.lang.OutOfMemoryError: Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 33MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:882)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:858)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:478)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:516)
	at org.onebusaway.android.report.ui.Open311ProblemFragment.onActivityResult(Open311ProblemFragment.java:447)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:175)
	at org.onebusaway.android.report.ui.BaseReportActivity.onActivityResult(BaseReportActivity.java:52)
	at android.app.Activity.dispatchActivityResult(Activity.java:7137)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
	at android.app.ActivityThread.access$1600(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
~~~

>When I report trash at a stop from OBA and try to submit a photo via the gallery, the app crashes. However it responds will by taking a picture.

Device was a Samsung Galaxy S5.

I can't reproduce this on a LG G5 w/ Android 7.0, LG G3 w/ Android 5.0.1, an Amazon Fire Phone (I believe Android 4.4.4), or a Nexus S 4G w/ Android 4.1.2.

**Steps to reproduce:** 

On an affected device:

1. Tap on "Send feedback->Report stop problem"
1. Tap on stop
1. Choose any issue category
1. Scroll down and tap on "Add Image" button, and then "Gallery"
1. Choose photo

**Expected behavior:** 

Add the photo to the issue report

**Observed behavior:** 

App crashes with OutOfMemoryError 

**Device and Android version:** 

~~~
Galaxy S5 (kltevzw)
Manufacturer Samsung 
Android version Android 4.4 
RAM (MB) 2048 
Screen size 1080 × 1920 
Screen density (dpi) 480 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8974
~~~

**Screenshots:** 

N/A

**Comment by barbeau** [comment]
Sounds like this is due to cramming a huge image into a small view.  See `OOMs and failing to allocate a bitmap` on this page: http://frescolib.org/docs/troubleshooting.html.

**Comment by barbeau** [comment]
See also https://developer.android.com/training/displaying-bitmaps/load-bitmap.html.

**Comment by barbeau** [comment]
To troubleshoot this and avoid polluting the live site, we should use the test SeeClickFix endpoint, which is available by setting the Regions API URL in donottranslate.xml to:
https://github.com/OneBusAway/onebusaway-multiregion-support/raw/testSeeClickFix/staging/regions-v3.json

...and we should be able see reports here:
https://test.seeclickfix.com/hillsborough-county-fl

**Comment by barbeau** [comment]
So the reason why the app isn't crashing when capturing an image from the camera is that apparently we're accidentally just grabbing a thumbnail from the result in `Open311ProblemFragment.onActivityResult()`, instead of getting the full size image.

Confirmed by https://developer.android.com/training/camera/photobasics.html#TaskPhotoView.

So in addition to fixing the OutOfMemory issue, we also want to attach full size photos taken with the camera to the Open311 submission.

**Comment by barbeau** [comment]
SeeClickFix says:

>You can submit any resolution that we will then process into an 800x600 image center cropped

So, there really isn't any point in submitting a photo larger than this in size, as it just increases wait time for upload via cellular connection and chance for failure.  So, we can scale down to this size before uploading.
