### ISSUE TITLE
"Fresh location" assertions in unit tests always fail

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#737]
**Summary:** 

I've been running the unit test suite locally more often because Travis is broken again (https://github.com/OneBusAway/onebusaway-android/issues/720), and the "fresh location" assertions in `LocationUtilsTest.testLocationApiV1()` and `LocationUtilsTest.testLocationServices()`) on newer devices always seem to fail.  These tests aren't run on emulators.  I'm guessing that Google changed the frequency with which they are updating location internally in newer versions of Android if no app has frequently requested location, which broke this test.  We can simply bump the threshold we're using for fresh locations up to 30 minutes, which I believe should resolve this (it's currently set to 5 minutes in `LocationUtilsText.FRESH_LOCATION_THRESHOLD_MS`.

**Steps to reproduce:** 

1. Uninstall existing app on device
1. Run the unit tests

**Expected behavior:** 

They should all pass on a real device.

**Observed behavior:** 

Two test failures related to `assertFreshLocation`:

~~~
junit.framework.AssertionFailedError
at org.onebusaway.android.util.test.LocationUtilsTest.assertFreshLocation(LocationUtilsTest.java:212)
at org.onebusaway.android.util.test.LocationUtilsTest.testLocationApiV1(LocationUtilsTest.java:183)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:198)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:183)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:560)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1939)
~~~

and

~~~
junit.framework.AssertionFailedError
at org.onebusaway.android.util.test.LocationUtilsTest.assertFreshLocation(LocationUtilsTest.java:212)
at org.onebusaway.android.util.test.LocationUtilsTest.testLocationServices(LocationUtilsTest.java:202)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:198)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:183)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:560)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1939)
~~~

**Device and Android version:** 

LG G5 w/ Android 7.0and Google Play services app 10.0.84 (440-137749526).

**Screenshots:** 

N/A

**Comment by barbeau** [comment]
Re-opening, I'm still occasionally seeing these same failures when running tests locally even with the bumped time threshold.
