### ISSUE TITLE
Hillsborough County Open311 test fails

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#826]
**Summary:** 

If you run the unit tests, `ReportProblemOpen311Test.testHillsboroughCounty()` fails with:

~~~
junit.framework.AssertionFailedError
at org.onebusaway.android.io.test.ReportProblemOpen311Test.testHillsboroughCounty(ReportProblemOpen311Test.java:103)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:198)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:183)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:560)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2102)
~~~

It looks like HART changed their Open311 service types (i.e., issue categories) so now only 3 are identified as "transit-related" based on heuristic keyword matching (a word-around because SeeClickFix doesn't support explicit groups or keywords in their Open311 API).  Our threshold for identifying deployments like HART where all services are transit-related is 4 (defined in `ReportConstants.NUM_TRANSIT_SERVICES_THRESHOLD`).

**Steps to reproduce:** 

Run the unit tests

**Expected behavior:** 

All tests should pass

**Observed behavior:** 

`ReportProblemOpen311Test.testHillsboroughCounty()` fails

**Device and Android version:** 

Reprod on Samsung Galaxy S8+ with Android 8.0 beta

**Comment by barbeau** [comment]
Best solution at this point seems to be to adapt our transit heuristics matching to include the word "passenger".  That brings our count of transit-related issues back up to be equal to the threshold at 4.  See below for the current list of HART services (i.e., issue categories).

![image](https://user-images.githubusercontent.com/928045/34275583-fbbd7a90-e66b-11e7-85a5-1ce40a78340d.png)

**Comment by barbeau** [comment]
For the record - this bug manifested in the app for HART service area with some issue categories being split into a "Transit" category, and other issues being split into an "Other" category in the issue category drop-down spinner list.  Because HART has their own SeeClickFix account and controls all the issue categories, all categories should show up under the "Transit" category.

**Comment by barbeau** [comment]
I'm seeing this again - looks like number of heuristic-matched transit-services for HART dipped to 3 again:

![image](https://user-images.githubusercontent.com/928045/35648573-2a9b4a92-06a4-11e8-91ab-8f280ab42f95.png)

**Comment by barbeau** [comment]
Heuristic matching is a headache.  Looks like HART is prefixing all of it's issues with "HART" now, so let's use that in the heuristic:

![image](https://user-images.githubusercontent.com/928045/49097061-01619f00-f23a-11e8-8018-ca5ce9590adb.png)

However, looks like the heuristic isn't picking up the arrival time record, as this test is failing too:

~~~
// There should only be one arrival times (trip) request type, because we treat that differently (show arrivals to pick from)
assertTrue(countDynamicTrip == 1);
~~~

**Comment by barbeau** [comment]
Actually, if we use "HART" in the stop heuristic, then it won't pick up the arrival time heuristic (hence the above), so that doesn't work...

**Comment by barbeau** [comment]
I'm just going to drop `NUM_TRANSIT_SERVICES_THRESHOLD` from 4 to 3.  We seem to consistently have at least 3 transit-related services for Hillsborough County, and not that many for Pinellas County, so 3 still works as a threshold and likely won't generate as many false negatives when looking for all transit properties.
