### ISSUE TITLE
Crash on Android P - Didn't find class "org.apache.http.ProtocolVersion"

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-android#949]
**Summary:** 

If you run the `nav` branch on Android P device, you get a crash with the following:

~~~
    Process: com.joulespersecond.seattlebusbot, PID: 7923
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at ez.b(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):3)
        at ey.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):3)
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):15)
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):6)
        at ed.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):21)
        at ed.run(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):8)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000000d/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000000d/MapsDynamite.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@14799084@14.7.99 (100700-223214910):4)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at ez.b(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):3) 
        at ey.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):3) 
        at fa.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):15) 
        at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):6) 
        at ed.a(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):21) 
        at ed.run(:com.google.android.gms.dynamite_mapsdynamite@14799084@14.7.99 (100700-223214910):8) 
~~~

The Android Maps SDK notes (https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library) now says:

>If your app is targeting API level 28 (Android 9.0) or above, you must include the following declaration within the `<application>` element of AndroidManifest.xml.
>
>     <uses-library
>            android:name="org.apache.http.legacy"
>       android:required="false" />
>If your app is targeting a lower API level, this is handled for you.

Curiously this doesn't happen on the master branch yet, so it must be a side effect of newer Maps API version in the nav branch, or a combination with other Firebase or Play Services features there.

**Steps to reproduce:** 

Run app on Android P device

**Expected behavior:** 

Not crash

**Observed behavior:** 

Crash

**Device and Android version:** 

Pixel 2 emulator w/ Android 9, build number PSR1.180720.075

**Comment by barbeau** [comment]
Actually, we aren't targeting 28 yet in the master branch (currently 26), which is why this didn't crash on the master branch.

**Comment by grndvl1** [comment]
We are seeing this even though we target 33

```
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lorg/apache/http/ProtocolVersion;
ahi.a
Caused by java.lang.ClassNotFoundException
org.apache.http.ProtocolVersion
ahi.a (:com.google.android.gms.policy_maps_core_dynamite@224910103@224910103065.509246174.509246174:25)
agp.a (:com.google.android.gms.policy_maps_core_dynamite@224910103@224910103065.509246174.509246174:14)
agp.run (:com.google.android.gms.policy_maps_core_dynamite@224910103@224910103065.509246174.509246174:2)
```
